#!/usr/bin/env bash
# shellcheck disable=SC2088  # tildes in log strings are display text
# Declarative symlink table.
#
# Every target that already exists as a real file is moved into a timestamped
# backup directory before being replaced. Nothing is ever deleted outright.

DOTFILES_BACKUP_ROOT="$HOME/.dotfiles-backup"
_backup_dir=""

# Created lazily so a fully idempotent run leaves no empty backup directories.
_ensure_backup_dir() {
    if [[ -z "$_backup_dir" ]]; then
        _backup_dir="$DOTFILES_BACKUP_ROOT/$(date +%Y%m%d-%H%M%S)"
        mkdir -p "$_backup_dir"
    fi
}

# link <source-relative-to-repo> <absolute-target>
link() {
    local src="$DOTFILES_DIR/$1"
    local dst="$2"
    local label="${dst/#$HOME/~}"

    [[ -e "$src" ]] || {
        warn "missing in repo, skipped: $1"
        return 0
    }

    mkdir -p "$(dirname "$dst")"

    if [[ -L "$dst" && "$(readlink "$dst")" == "$src" ]]; then
        skip "$label"
        return 0
    fi

    if [[ -e "$dst" || -L "$dst" ]]; then
        _ensure_backup_dir
        local rel="${dst#"$HOME"/}"
        mkdir -p "$(dirname "$_backup_dir/$rel")"
        mv "$dst" "$_backup_dir/$rel"
        warn "backed up existing $label"
    fi

    ln -s "$src" "$dst"
    ok "$label"
}

links_apply() {
    info "Linking dotfiles..."

    link "zsh/.zshrc" "$HOME/.zshrc"
    link "zsh/.zprofile" "$HOME/.zprofile"
    link "git/gitconfig" "$HOME/.gitconfig"
    link "ssh/config" "$HOME/.ssh/config"

    mkdir -p "$HOME/Dev"
    chmod 700 "$HOME/.ssh" 2>/dev/null || true

    links_write_git_base
    links_install_git_hooks
    claude_settings_apply

    if [[ -n "$_backup_dir" ]]; then
        info "Replaced files were saved to ${_backup_dir/#$HOME/~}"
    fi
}

# Points git at the personal identity using an absolute path computed here, so
# nothing in the repo has to assume where the repo lives. Written by --link
# alone, which means git works without any vault access.
links_write_git_base() {
    local dst="$HOME/.gitconfig.base.local"
    {
        echo "# generated by install.sh — do not edit"
        echo "[include]"
        echo "    path = $DOTFILES_DIR/profiles/personal/gitconfig"
    } >"$dst"
    ok "~/.gitconfig.base.local"

    # The base turns commit signing on, but the key only arrives with
    # --sync-overlay. Without this placeholder a fresh clone cannot commit at
    # all. --sync-overlay overwrites it with the real key.
    if [[ ! -f "$HOME/.gitconfig.local" ]]; then
        {
            echo "# generated by install.sh — replaced by --sync-overlay"
            echo "[commit]"
            echo "    gpgsign = false"
        } >"$HOME/.gitconfig.local"
        warn "commits are unsigned until: ./install.sh --sync-overlay"
    fi
}

# The pre-commit hook is the last line of defence against committing a client
# name into a repository that must stay neutral.
links_install_git_hooks() {
    local hook_src="$DOTFILES_DIR/hooks/pre-commit"
    local hook_dst="$DOTFILES_DIR/.git/hooks/pre-commit"

    [[ -d "$DOTFILES_DIR/.git" ]] || return 0
    [[ -f "$hook_src" ]] || return 0

    mkdir -p "$(dirname "$hook_dst")"
    if [[ -L "$hook_dst" && "$(readlink "$hook_dst")" == "$hook_src" ]]; then
        skip "git pre-commit hook"
        return 0
    fi
    [[ -e "$hook_dst" ]] && mv "$hook_dst" "$hook_dst.bak"
    ln -s "$hook_src" "$hook_dst"
    ok "git pre-commit hook"
}

# Report on link health without changing anything.
links_check() {
    local -a pairs=(
        "zsh/.zshrc:$HOME/.zshrc"
        "zsh/.zprofile:$HOME/.zprofile"
        "git/gitconfig:$HOME/.gitconfig"
        "ssh/config:$HOME/.ssh/config"
    )
    local rc=0 entry src dst
    for entry in "${pairs[@]}"; do
        src="$DOTFILES_DIR/${entry%%:*}"
        dst="${entry#*:}"
        if [[ -L "$dst" && "$(readlink "$dst")" == "$src" ]]; then
            ok "${dst/#$HOME/~}"
        else
            err "${dst/#$HOME/~} is not linked to the repo"
            rc=1
        fi
    done
    return $rc
}
