#!/usr/bin/env bash
# shellcheck disable=SC2088  # tildes in log strings are display text
# Overlay materialization: pull a job's configuration out of its own vault and
# write it to machine-local files that the repo never sees.

OVERLAY_ITEM="dotfiles-overlay"
OVERLAY_FORGE_HOSTS="github.com"
GEN_HEADER="# generated by install.sh — do not edit"

overlay_source_provider() {
    local impl="$DOTFILES_DIR/lib/providers/${DOTFILES_PROVIDER}.sh"
    [[ -f "$impl" ]] || die "unknown provider: $DOTFILES_PROVIDER"
    # shellcheck source=/dev/null
    source "$impl"
}

_expand_home() { printf '%s' "${1/#\~/$HOME}"; }

_fetch_or() { provider_fetch "$1" 2>/dev/null || printf '%s' "${2:-}"; }

_write_generated() {
    local dst="$1"
    mkdir -p "$(dirname "$dst")"
    {
        echo "$GEN_HEADER"
        cat
    } >"$dst"
}

# ---------------------------------------------------------------- signing key

# Find the key this machine should sign with, preferring one that ALREADY
# exists. Creating a second key when a perfectly good one is sitting in the
# vault just means another key to register on every forge.
#
# Sets DOTFILES_KEY_ITEM / DOTFILES_KEY_VAULT and persists them.
overlay_resolve_signing_key() {
    local default_item="$1" default_vault="$2"

    # Already pinned by a previous run or by an explicit flag.
    if [[ -n "$DOTFILES_KEY_ITEM" ]]; then
        [[ -z "$DOTFILES_KEY_VAULT" ]] && DOTFILES_KEY_VAULT="$default_vault"
        return 0
    fi

    local -a keys=()
    while IFS= read -r line; do
        [[ -n "$line" ]] && keys+=("$line")
    done < <(provider_list_keys 2>/dev/null)

    case ${#keys[@]} in
        0)
            DOTFILES_KEY_ITEM="$default_item"
            DOTFILES_KEY_VAULT="$default_vault"
            ;;
        1)
            DOTFILES_KEY_VAULT="${keys[0]%%$'\t'*}"
            DOTFILES_KEY_ITEM="${keys[0]#*$'\t'}"
            ok "Reusing existing signing key: $DOTFILES_KEY_ITEM (vault $DOTFILES_KEY_VAULT)" >&2
            ;;
        *)
            # Picking the wrong signing key is silent and long-lived, so never
            # guess one without a human at the keyboard.
            if [[ ! -t 0 ]]; then
                err "Several SSH keys exist; refusing to guess without a terminal."
                err "Re-run interactively, or pass:"
                err "  ./install.sh --sync-overlay --signing-key-item NAME --signing-key-vault VAULT"
                provider_list_keys | while IFS=$'\t' read -r v t; do
                    printf '    --signing-key-item "%s" --signing-key-vault "%s"\n' "$t" "$v" >&2
                done
                exit 1
            fi
            echo >&2
            info "Existing SSH keys in your vault:" >&2
            local i=1 line
            for line in "${keys[@]}"; do
                printf '  %d) %s   [vault: %s]\n' "$i" "${line#*$'\t'}" "${line%%$'\t'*}" >&2
                i=$((i + 1))
            done
            printf '  %d) create a new one called %s\n' "$i" "$default_item" >&2
            echo >&2
            printf 'Which key should sign your commits? [1] ' >&2
            local reply
            read -r reply || reply=1
            [[ -z "$reply" ]] && reply=1
            if [[ "$reply" == "$i" ]]; then
                DOTFILES_KEY_ITEM="$default_item"
                DOTFILES_KEY_VAULT="$default_vault"
            else
                line="${keys[$((reply - 1))]}"
                DOTFILES_KEY_VAULT="${line%%$'\t'*}"
                DOTFILES_KEY_ITEM="${line#*$'\t'}"
            fi
            ;;
    esac

    profile_save >/dev/null
}

# Echoes the public key on stdout. Everything else goes to stderr.
# overlay_ensure_signing_key <item> [vault]
overlay_ensure_signing_key() {
    local item="$1" vault="${2:-}" pub

    if pub="$(provider_pubkey "$item" "$vault")" && [[ -n "$pub" && "$pub" != "null" ]]; then
        printf '%s' "$pub"
        return 0
    fi

    if ! provider_supports_keygen; then
        err "No signing key found in vault (item: $item)"
        echo >&2
        provider_keygen_hint "$item" >&2
        return 1
    fi

    step "No signing key found — creating '$item' in the vault..." >&2
    provider_create_key "$item" "$vault" >&2 || {
        err "Could not create the signing key"
        return 1
    }

    pub="$(provider_pubkey "$item" "$vault")" || {
        err "Key created but its public half could not be read back"
        return 1
    }
    ok "Generated signing key '$item' (private half stays in the vault)" >&2
    printf '%s' "$pub"
}

# Without this, `git log --show-signature` reports "No principal matched" even
# for perfectly valid signatures.
overlay_write_allowed_signers() {
    local dst="$1" email="$2" pub="$3"
    mkdir -p "$(dirname "$dst")"
    printf '%s %s\n' "$email" "$pub" >"$dst"
    chmod 600 "$dst"
}

# ------------------------------------------------------------------ generated

# With two GitHub accounts in one agent, the forge accepts whichever key
# authenticates first — which can silently be the wrong account. IdentitiesOnly
# plus an explicit public key restricts the agent to exactly one identity.
#
# overlay_write_ssh_config_local <pubkey-file> [forge-hosts]
overlay_write_ssh_config_local() {
    local keyfile="${1:-}" hosts="${2:-github.com}"
    local socket personal_key host
    socket="$(provider_agent_socket)"
    personal_key="$DOTFILES_CONFIG_DIR/auth_key.pub"

    {
        echo
        echo "Host *"
        echo "    IdentityAgent \"$socket\""

        if [[ -n "$keyfile" && -f "$keyfile" ]]; then
            for host in $hosts; do
                echo
                echo "Host $host"
                echo "    HostName $host"
                echo "    User git"
                echo "    IdentityAgent \"$socket\""
                echo "    IdentitiesOnly yes"
                echo "    IdentityFile $keyfile"
            done
        fi

        # A client machine still has to reach the personal account to pull these
        # dotfiles, so keep one alias pinned to the personal key.
        if [[ "$DOTFILES_PROFILE" == "work" && -f "$personal_key" ]]; then
            echo
            echo "Host github-personal"
            echo "    HostName github.com"
            echo "    User git"
            echo "    IdentityAgent \"$socket\""
            echo "    IdentitiesOnly yes"
            echo "    IdentityFile $personal_key"
        fi
    } | _write_generated "$HOME/.ssh/config.local"

    chmod 600 "$HOME/.ssh/config.local"
    if [[ -n "$keyfile" && -f "$keyfile" ]]; then
        ok "~/.ssh/config.local pins ${hosts// /, } to one identity"
    else
        ok "~/.ssh/config.local -> ${socket/#$HOME/~}"
    fi
}

# `ssh-keygen -Y sign` - git's signer when gpg.ssh.program is unset - ignores
# IdentityAgent in ssh_config and reads SSH_AUTH_SOCK. Without this, signing
# fails on every machine that does not use a vendor signer (all Bitwarden ones).
overlay_write_agent_env() {
    local socket
    socket="$(provider_agent_socket)"
    {
        echo "# generated by install.sh - do not edit"
        echo "export SSH_AUTH_SOCK=\"$socket\""
    } >"$DOTFILES_CONFIG_DIR/agent-env.sh"
    ok "~/.config/dotfiles/agent-env.sh"
}

overlay_write_pubkey_file() {
    local dst="$1" pub="$2"
    mkdir -p "$(dirname "$dst")"
    printf '%s\n' "$pub" >"$dst"
    chmod 644 "$dst"
}

# On a client machine the dotfiles repo itself lives in the PERSONAL account,
# so its remote must not go through the pinned work identity.
overlay_retarget_own_remote() {
    [[ "$DOTFILES_PROFILE" == "work" ]] || return 0
    [[ -f "$DOTFILES_CONFIG_DIR/auth_key.pub" ]] || return 0

    local url
    url="$(git -C "$DOTFILES_DIR" remote get-url origin 2>/dev/null || true)"
    case "$url" in
        *github-personal:*) return 0 ;;
        git@github.com:* | ssh://git@github.com/*)
            local path="${url#*github.com[:/]}"
            git -C "$DOTFILES_DIR" remote set-url origin "git@github-personal:$path"
            ok "dotfiles remote now uses the personal identity"
            ;;
    esac
}

# 1Password-only artifact. A Bitwarden machine never gets one.
overlay_write_agent_toml() {
    local keys_fragment="$1"
    local dst="$HOME/.config/1Password/ssh/agent.toml"

    if ! provider_uses_agent_toml; then
        [[ -e "$dst" ]] && {
            rm -f "$dst"
            warn "removed stale $dst (provider is $DOTFILES_PROVIDER)"
        }
        return 0
    fi

    mkdir -p "$(dirname "$dst")"
    {
        echo "$GEN_HEADER"
        cat "$DOTFILES_DIR/1Password/ssh/agent.base.toml"
        # A client machine has its own 1Password account with its own keys.
        # Mounting the personal account's vaults there would be both useless
        # and a leak of where personal secrets live.
        if [[ "$DOTFILES_PROFILE" == "personal" ]]; then
            echo
            cat "$DOTFILES_DIR/profiles/base/agent-keys.toml"
        fi
        if [[ -n "$keys_fragment" ]]; then
            echo
            printf '%s\n' "$keys_fragment"
        fi
    } >"$dst"
    ok "~/.config/1Password/ssh/agent.toml"
}

# ----------------------------------------------------------------- entrypoint

# Fresh-Mac path. brew has just installed the CLI and the desktop app, but
# signing in and enabling the SSH agent can only be done by a human. Rather
# than dying halfway through a new machine's setup, guide and retry.
overlay_bootstrap() {
    overlay_source_provider

    if ! provider_require 2>/dev/null; then
        err "The ${DOTFILES_PROVIDER} CLI is still missing after package installation."
        overlay_write_deferred_guard
        return 1
    fi

    local app reply attempt=0
    app="$(provider_gui_app)"
    [[ -d "$app" ]] || warn "${app##*/} is not installed yet; the SSH agent lives in that app"

    while ! provider_ready; do
        attempt=$((attempt + 1))
        if [[ $attempt -gt 3 ]]; then
            warn "Still not reachable. Finishing the rest of the setup."
            overlay_write_deferred_guard
            return 1
        fi
        echo
        provider_setup_hint
        echo
        printf 'Press Enter once that is done, or type s to skip for now: '
        read -r reply || reply="s"
        if [[ "$reply" == "s" || "$reply" == "S" ]]; then
            overlay_write_deferred_guard
            return 1
        fi
    done

    overlay_sync
}

# When the vault could not be reached we must NOT leave a machine that quietly
# commits under the wrong identity. On a client machine we strip every identity
# so git refuses to commit at all until --sync-overlay succeeds.
overlay_write_deferred_guard() {
    if [[ "$DOTFILES_PROFILE" == "work" ]]; then
        {
            echo "$GEN_HEADER"
            echo "# Overlay not synced yet: no identity is configured on purpose."
        } >"$HOME/.gitconfig.base.local"
        {
            echo
            echo "[user]"
            echo "    useConfigOnly = true"
            echo "[commit]"
            echo "    gpgsign = false"
        } | _write_generated "$HOME/.gitconfig.local"
        warn "git will REFUSE to commit on this machine until: ./install.sh --sync-overlay"
    else
        {
            echo
            echo "[commit]"
            echo "    gpgsign = false"
        } | _write_generated "$HOME/.gitconfig.local"
        warn "commits will be unsigned until: ./install.sh --sync-overlay"
    fi
}

overlay_sync() {
    overlay_source_provider
    provider_require
    provider_unlock

    # Restore the personal include in case a previous run left the guard behind.
    links_write_git_base >/dev/null

    local sign_program allowed_signers pub email name
    sign_program="$(provider_ssh_sign_program)"

    if [[ "$DOTFILES_PROFILE" == "personal" ]]; then
        overlay_sync_personal "$sign_program"
    else
        overlay_sync_work "$sign_program"
    fi
}

overlay_sync_personal() {
    local sign_program="$1"
    local allowed_signers="$DOTFILES_CONFIG_DIR/allowed_signers"
    local email pub

    email="$(git config --file "$DOTFILES_DIR/profiles/personal/gitconfig" user.email || true)"
    [[ -n "$email" ]] || die "profiles/personal/gitconfig has no user.email"

    overlay_resolve_signing_key "git-signing-key" "${DOTFILES_VAULT:-Private}"
    if ! pub="$(overlay_ensure_signing_key "$DOTFILES_KEY_ITEM" "$DOTFILES_KEY_VAULT")"; then
        die "Cannot continue without a signing key"
    fi

    overlay_write_allowed_signers "$allowed_signers" "$email" "$pub"

    {
        echo
        echo "[user]"
        echo "    signingkey = $pub"
        echo "[gpg \"ssh\"]"
        echo "    allowedSignersFile = $allowed_signers"
        [[ -n "$sign_program" ]] && echo "    program = $sign_program"
    } | _write_generated "$HOME/.gitconfig.local"
    ok "~/.gitconfig.local (personal identity)"

    overlay_write_pubkey_file "$DOTFILES_CONFIG_DIR/auth_key.pub" "$pub"
    overlay_write_agent_toml "$(cat "$DOTFILES_DIR/profiles/personal/agent-keys.toml")"
    overlay_write_ssh_config_local "$DOTFILES_CONFIG_DIR/auth_key.pub" "$OVERLAY_FORGE_HOSTS"
    overlay_write_agent_env

    overlay_announce_key "$pub"
}

overlay_sync_work() {
    local sign_program="$1"
    local email name workdir key_item zsh_frag brew_frag agent_frag pub

    mkdir -p "$DOTFILES_LOCAL"
    chmod 700 "$DOTFILES_LOCAL"

    provider_load_overlay ||
        die "No '$OVERLAY_ITEM' item found in the vault. Create it first (see README)."

    email="$(_fetch_or email)"
    [[ -n "$email" ]] || die "overlay item is missing the required 'email' field"
    name="$(_fetch_or name "Andres Morelos")"
    workdir="$(_expand_home "$(_fetch_or workdir "$HOME/Dev/$DOTFILES_SLUG")")"
    key_item="$(_fetch_or signing-key-item "git-signing-key")"
    zsh_frag="$(_fetch_or zsh)"
    brew_frag="$(_fetch_or brewfile)"
    agent_frag="$(_fetch_or agent-keys)"

    # git silently ignores a relative gitdir: pattern, so force an absolute path.
    [[ "$workdir" != /* ]] && workdir="$HOME/${workdir#./}"
    [[ "$workdir" != */ ]] && workdir="$workdir/"
    mkdir -p "$workdir"

    overlay_resolve_signing_key "$key_item" "$DOTFILES_VAULT"
    if ! pub="$(overlay_ensure_signing_key "$DOTFILES_KEY_ITEM" "$DOTFILES_KEY_VAULT")"; then
        die "Cannot continue without a signing key"
    fi

    overlay_write_allowed_signers "$DOTFILES_LOCAL/allowed_signers" "$email" "$pub"

    # The job identity, applied only inside its own working directory.
    {
        echo
        echo "[user]"
        echo "    email = $email"
        echo "    name = $name"
        echo "    signingkey = $pub"
        echo "[commit]"
        echo "    gpgsign = true"
        echo "[gpg \"ssh\"]"
        echo "    allowedSignersFile = $DOTFILES_LOCAL/allowed_signers"
        [[ -n "$sign_program" ]] && echo "    program = $sign_program"
    } | _write_generated "$DOTFILES_LOCAL/gitconfig"
    chmod 600 "$DOTFILES_LOCAL/gitconfig"

    # Signing is off by default on a client machine: the personal key lives in a
    # vault this machine cannot reach, so a global gpgsign would only ever fail.
    {
        echo
        echo "[commit]"
        echo "    gpgsign = false"
        echo
        echo "[includeIf \"gitdir:$workdir\"]"
        echo "    path = $DOTFILES_LOCAL/gitconfig"
    } | _write_generated "$HOME/.gitconfig.local"
    ok "~/.gitconfig.local -> work identity under ${workdir/#$HOME/~}"

    [[ -n "$zsh_frag" ]] && {
        printf '%s\n' "$zsh_frag" | _write_generated "$DOTFILES_LOCAL/zsh.zsh"
        ok "overlay zsh fragment"
    }
    [[ -n "$brew_frag" ]] && {
        printf '%s\n' "$brew_frag" | _write_generated "$DOTFILES_LOCAL/Brewfile"
        ok "overlay Brewfile"
    }

    overlay_write_pubkey_file "$DOTFILES_LOCAL/auth_key.pub" "$pub"
    overlay_write_agent_toml "$agent_frag"
    overlay_write_ssh_config_local "$DOTFILES_LOCAL/auth_key.pub" "$(_fetch_or forge-hosts "github.com")"
    overlay_write_agent_env
    overlay_retarget_own_remote

    overlay_announce_key "$pub"
}

# The one step that cannot be automated: only the client can register the key
# on their own GitHub/GitLab account.
overlay_announce_key() {
    echo
    info "Signing public key for this profile:"
    printf '%s\n' "  $1"
    echo
    step "Register it as a SIGNING key (not just an auth key):"
    echo "  GitHub  -> Settings > SSH and GPG keys > New SSH key > type: Signing Key"
    echo "  GitLab  -> Preferences > SSH Keys > Usage type: Signing"
    echo "  Re-print any time with: ./install.sh --show-signing-key"
    echo
}

overlay_purge() {
    local removed=0
    for target in "$HOME/.dotfiles-local" "$HOME/.gitconfig.local" "$HOME/.gitconfig.base.local" "$HOME/.ssh/config.local" \
        "$HOME/.config/1Password/ssh/agent.toml" "$DOTFILES_CONFIG_DIR/allowed_signers" "$DOTFILES_CONFIG_DIR/auth_key.pub" "$DOTFILES_CONFIG_DIR/agent-env.sh"; do
        if [[ -e "$target" ]]; then
            rm -rf "$target"
            ok "removed ${target/#$HOME/~}"
            removed=1
        fi
    done
    [[ $removed -eq 0 ]] && skip "nothing to purge"
    warn "Machine profile at ${DOTFILES_CONFIG_FILE/#$HOME/~} was kept. Delete it too if you are handing the machine back."
    return 0
}
