#!/usr/bin/env bash
# shellcheck disable=SC2088  # tildes in log strings are display text
# Overlay materialization: pull a job's configuration out of its own vault and
# write it to machine-local files that the repo never sees.

OVERLAY_ITEM="dotfiles-overlay"
GEN_HEADER="# generated by install.sh — do not edit"

overlay_source_provider() {
    local impl="$DOTFILES_DIR/lib/providers/${DOTFILES_PROVIDER}.sh"
    [[ -f "$impl" ]] || die "unknown provider: $DOTFILES_PROVIDER"
    # shellcheck source=/dev/null
    source "$impl"
}

_expand_home() { printf '%s' "${1/#\~/$HOME}"; }

_fetch_or() { provider_fetch "$1" 2>/dev/null || printf '%s' "${2:-}"; }

_write_generated() {
    local dst="$1"
    mkdir -p "$(dirname "$dst")"
    {
        echo "$GEN_HEADER"
        cat
    } >"$dst"
}

# ---------------------------------------------------------------- signing key

# Echoes the public key on stdout. Everything else goes to stderr.
overlay_ensure_signing_key() {
    local item="$1" pub

    if pub="$(provider_pubkey "$item")" && [[ -n "$pub" && "$pub" != "null" ]]; then
        printf '%s' "$pub"
        return 0
    fi

    if ! provider_supports_keygen; then
        err "No signing key found in vault (item: $item)"
        echo >&2
        provider_keygen_hint "$item" >&2
        return 1
    fi

    step "No signing key found — creating '$item' in the vault..." >&2
    provider_create_key "$item" >&2 || {
        err "Could not create the signing key"
        return 1
    }

    pub="$(provider_pubkey "$item")" || {
        err "Key created but its public half could not be read back"
        return 1
    }
    ok "Generated signing key '$item' (private half stays in the vault)" >&2
    printf '%s' "$pub"
}

# Without this, `git log --show-signature` reports "No principal matched" even
# for perfectly valid signatures.
overlay_write_allowed_signers() {
    local dst="$1" email="$2" pub="$3"
    mkdir -p "$(dirname "$dst")"
    printf '%s %s\n' "$email" "$pub" >"$dst"
    chmod 600 "$dst"
}

# ------------------------------------------------------------------ generated

overlay_write_ssh_config_local() {
    local socket
    socket="$(provider_agent_socket)"
    _write_generated "$HOME/.ssh/config.local" <<EOF

Host *
    IdentityAgent "$socket"
EOF
    chmod 600 "$HOME/.ssh/config.local"
    ok "~/.ssh/config.local -> ${socket/#$HOME/~}"
}

# 1Password-only artifact. A Bitwarden machine never gets one.
overlay_write_agent_toml() {
    local keys_fragment="$1"
    local dst="$HOME/.config/1Password/ssh/agent.toml"

    if ! provider_uses_agent_toml; then
        [[ -e "$dst" ]] && {
            rm -f "$dst"
            warn "removed stale $dst (provider is $DOTFILES_PROVIDER)"
        }
        return 0
    fi

    mkdir -p "$(dirname "$dst")"
    {
        echo "$GEN_HEADER"
        cat "$DOTFILES_DIR/1Password/ssh/agent.base.toml"
        echo
        cat "$DOTFILES_DIR/profiles/base/agent-keys.toml"
        if [[ -n "$keys_fragment" ]]; then
            echo
            printf '%s\n' "$keys_fragment"
        fi
    } >"$dst"
    ok "~/.config/1Password/ssh/agent.toml"
}

# ----------------------------------------------------------------- entrypoint

# Fresh-Mac path. brew has just installed the CLI and the desktop app, but
# signing in and enabling the SSH agent can only be done by a human. Rather
# than dying halfway through a new machine's setup, guide and retry.
overlay_bootstrap() {
    overlay_source_provider

    if ! provider_require 2>/dev/null; then
        err "The ${DOTFILES_PROVIDER} CLI is still missing after package installation."
        overlay_write_deferred_guard
        return 1
    fi

    local app reply attempt=0
    app="$(provider_gui_app)"
    [[ -d "$app" ]] || warn "${app##*/} is not installed yet; the SSH agent lives in that app"

    while ! provider_ready; do
        attempt=$((attempt + 1))
        if [[ $attempt -gt 3 ]]; then
            warn "Still not reachable. Finishing the rest of the setup."
            overlay_write_deferred_guard
            return 1
        fi
        echo
        provider_setup_hint
        echo
        printf 'Press Enter once that is done, or type s to skip for now: '
        read -r reply || reply="s"
        if [[ "$reply" == "s" || "$reply" == "S" ]]; then
            overlay_write_deferred_guard
            return 1
        fi
    done

    overlay_sync
}

# When the vault could not be reached we must NOT leave a machine that quietly
# commits under the wrong identity. On a client machine we strip every identity
# so git refuses to commit at all until --sync-overlay succeeds.
overlay_write_deferred_guard() {
    if [[ "$DOTFILES_PROFILE" == "work" ]]; then
        {
            echo "$GEN_HEADER"
            echo "# Overlay not synced yet: no identity is configured on purpose."
        } >"$HOME/.gitconfig.base.local"
        {
            echo
            echo "[user]"
            echo "    useConfigOnly = true"
            echo "[commit]"
            echo "    gpgsign = false"
        } | _write_generated "$HOME/.gitconfig.local"
        warn "git will REFUSE to commit on this machine until: ./install.sh --sync-overlay"
    else
        {
            echo
            echo "[commit]"
            echo "    gpgsign = false"
        } | _write_generated "$HOME/.gitconfig.local"
        warn "commits will be unsigned until: ./install.sh --sync-overlay"
    fi
}

overlay_sync() {
    overlay_source_provider
    provider_require
    provider_unlock

    # Restore the personal include in case a previous run left the guard behind.
    links_write_git_base >/dev/null

    local sign_program allowed_signers pub email name
    sign_program="$(provider_ssh_sign_program)"

    if [[ "$DOTFILES_PROFILE" == "personal" ]]; then
        overlay_sync_personal "$sign_program"
    else
        overlay_sync_work "$sign_program"
    fi

    overlay_write_ssh_config_local
}

overlay_sync_personal() {
    local sign_program="$1"
    local key_item="${DOTFILES_SIGNING_KEY_ITEM:-git-signing-key}"
    local allowed_signers="$DOTFILES_CONFIG_DIR/allowed_signers"
    local email pub

    email="$(git config --file "$DOTFILES_DIR/profiles/personal/gitconfig" user.email || true)"
    [[ -n "$email" ]] || die "profiles/personal/gitconfig has no user.email"

    if ! pub="$(overlay_ensure_signing_key "$key_item")"; then
        die "Cannot continue without a signing key"
    fi

    overlay_write_allowed_signers "$allowed_signers" "$email" "$pub"

    {
        echo
        echo "[user]"
        echo "    signingkey = $pub"
        echo "[gpg \"ssh\"]"
        echo "    allowedSignersFile = $allowed_signers"
        [[ -n "$sign_program" ]] && echo "    program = $sign_program"
    } | _write_generated "$HOME/.gitconfig.local"
    ok "~/.gitconfig.local (personal identity)"

    overlay_write_agent_toml "$(cat "$DOTFILES_DIR/profiles/personal/agent-keys.toml")"

    overlay_announce_key "$pub"
}

overlay_sync_work() {
    local sign_program="$1"
    local email name workdir key_item zsh_frag brew_frag agent_frag pub

    mkdir -p "$DOTFILES_LOCAL"
    chmod 700 "$DOTFILES_LOCAL"

    provider_load_overlay ||
        die "No '$OVERLAY_ITEM' item found in the vault. Create it first (see README)."

    email="$(_fetch_or email)"
    [[ -n "$email" ]] || die "overlay item is missing the required 'email' field"
    name="$(_fetch_or name "Andres Morelos")"
    workdir="$(_expand_home "$(_fetch_or workdir "$HOME/Dev/$DOTFILES_SLUG")")"
    key_item="$(_fetch_or signing-key-item "git-signing-key")"
    zsh_frag="$(_fetch_or zsh)"
    brew_frag="$(_fetch_or brewfile)"
    agent_frag="$(_fetch_or agent-keys)"

    # git silently ignores a relative gitdir: pattern, so force an absolute path.
    [[ "$workdir" != /* ]] && workdir="$HOME/${workdir#./}"
    [[ "$workdir" != */ ]] && workdir="$workdir/"
    mkdir -p "$workdir"

    if ! pub="$(overlay_ensure_signing_key "$key_item")"; then
        die "Cannot continue without a signing key"
    fi

    overlay_write_allowed_signers "$DOTFILES_LOCAL/allowed_signers" "$email" "$pub"

    # The job identity, applied only inside its own working directory.
    {
        echo
        echo "[user]"
        echo "    email = $email"
        echo "    name = $name"
        echo "    signingkey = $pub"
        echo "[commit]"
        echo "    gpgsign = true"
        echo "[gpg \"ssh\"]"
        echo "    allowedSignersFile = $DOTFILES_LOCAL/allowed_signers"
        [[ -n "$sign_program" ]] && echo "    program = $sign_program"
    } | _write_generated "$DOTFILES_LOCAL/gitconfig"
    chmod 600 "$DOTFILES_LOCAL/gitconfig"

    # Signing is off by default on a client machine: the personal key lives in a
    # vault this machine cannot reach, so a global gpgsign would only ever fail.
    {
        echo
        echo "[commit]"
        echo "    gpgsign = false"
        echo
        echo "[includeIf \"gitdir:$workdir\"]"
        echo "    path = $DOTFILES_LOCAL/gitconfig"
    } | _write_generated "$HOME/.gitconfig.local"
    ok "~/.gitconfig.local -> work identity under ${workdir/#$HOME/~}"

    [[ -n "$zsh_frag" ]] && {
        printf '%s\n' "$zsh_frag" | _write_generated "$DOTFILES_LOCAL/zsh.zsh"
        ok "overlay zsh fragment"
    }
    [[ -n "$brew_frag" ]] && {
        printf '%s\n' "$brew_frag" | _write_generated "$DOTFILES_LOCAL/Brewfile"
        ok "overlay Brewfile"
    }

    overlay_write_agent_toml "$agent_frag"
    overlay_announce_key "$pub"
}

# The one step that cannot be automated: only the client can register the key
# on their own GitHub/GitLab account.
overlay_announce_key() {
    echo
    info "Signing public key for this profile:"
    printf '%s\n' "  $1"
    echo
    step "Register it as a SIGNING key (not just an auth key):"
    echo "  GitHub  -> Settings > SSH and GPG keys > New SSH key > type: Signing Key"
    echo "  GitLab  -> Preferences > SSH Keys > Usage type: Signing"
    echo "  Re-print any time with: ./install.sh --show-signing-key"
    echo
}

overlay_purge() {
    local removed=0
    for target in "$HOME/.dotfiles-local" "$HOME/.gitconfig.local" "$HOME/.gitconfig.base.local" "$HOME/.ssh/config.local" \
        "$HOME/.config/1Password/ssh/agent.toml" "$DOTFILES_CONFIG_DIR/allowed_signers"; do
        if [[ -e "$target" ]]; then
            rm -rf "$target"
            ok "removed ${target/#$HOME/~}"
            removed=1
        fi
    done
    [[ $removed -eq 0 ]] && skip "nothing to purge"
    warn "Machine profile at ${DOTFILES_CONFIG_FILE/#$HOME/~} was kept. Delete it too if you are handing the machine back."
    return 0
}
